### ISSUE TITLE
project card when having changes in split properties e.g. lanes, ttime_assert, price, etc.

### ISSUE THREAD

**Issue by i-am-sijia** [wsp-sag/Lasso#48]
Network standard:

`lanes : 2`

MetC base network (product of Lasso):

```
lanes_AM : 2,
lanes_MD : 2,
lanes_PM : 2,
lanes_NT : 2
```

Cube logfile (user input):

```
lanes_AM : 3,
lanes_MD : 2,
lanes_PM : 3,
lanes_NT : 2
```

project card can be: 

```
- property: lanes_AM
   existing: 2
   set: 3
- property: lanes_PM
   existing: 2
   set: 3

```
Question: does network wrangler like this if lanes_AM and lanes_PM does not exist in network standard?  Do we need to change network standard?

@e-lo

**Comment by e-lo** [comment]
The project card should look like:

```
  - property: lanes
    set: 2
    timeofday:
      - time: ['6:00', '9:00']
        set: 3
      - time: ['16:00', '19:00']
        set: 3
```

The RoadwayNetwork in translates this standard to AM/MD/PM when it does the write out...so we need to do it on the read-in as well. I'll take a look.
