### ISSUE TITLE
Project card structure changed after refactoring project.py

### ISSUE THREAD

**Issue by i-am-sijia** [wsp-sag/Lasso#85]
@e-lo In my tests, the link changes are not structured correctly, e.g. for Lanes and Price.  Is it intentional?

It used to be
```
- category: Roadway Attribute Change
  facility:
    link:
      - model_link_id:
        - 224
  properties:
  - existing: 1
    property: lanes
    timeofday:
    - set: 2
      time:
      - '6:00'
      - '9:00'
    - set: 3
      time:
      - '9:00'
      - '16:00'
    - set: 2
      time:
      - '16:00'
      - '19:00'
    - set: 3
      time:
      - '19:00'
      - '6:00'
```

but now it's

```
- category: Roadway Property Change
  facility:
    link:
    - model_link_id:
      - 224
  properties:
    existing: 1
    property: lanes_AM
    set: 2
- category: Roadway Property Change
  facility:
    link:
    - model_link_id:
      - 224
  properties:
    existing: 1
    property: lanes_PM
    set: 2
- category: Roadway Property Change
  facility:
    link:
    - model_link_id:
      - 224
  properties:
    existing: 1
    property: lanes_MD
    set: 3
- category: Roadway Property Change
  facility:
    link:
    - model_link_id:
      - 224
  properties:
    existing: 1
    property: lanes_NT
    set: 3
```
